name: quantecon
channels:
  - default
dependencies:
  - python=3.8
  - anaconda=2020.11
  - pip
  - pip:
    - jupytext
    - jupyter-book
    - jupinx
    - sphinx-multitoc-numbering
    - quantecon-book-theme
    - joblib
    - interpolation
    - ghp-import

