name: Test QuantEcon Environment
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 22 * * *'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Anaconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: quantecon
      - name: Run lecture-python-programming.myst
        shell: bash -l {0}
        run: |
          git clone https://github.com/quantecon/lecture-python-programming.myst
          cd lecture-python-programming.myst
          jb build lectures
      - name: Run lecture-python.myst
        shell: bash -l {0}
        run: |
          git clone https://github.com/quantecon/lecture-python.myst
          cd lecture-python.myst
          jb build lectures
      # - name: Run lecture-python-advanced.myst
      #   shell: bash -l {0}
      #   run: |
      #     git clone https://github.com/quantecon/lecture-python-advanced.myst
      #     cd lecture-python-advanced.myst
      #     jb build lectures